
export const routes = [

    {value: [] , name: '4th match flame' },
    {value: [] , name: 'AEDD' },
    {value: [] , name: 'Ardor blossom star' },
    {value: [] , name: 'Bodysack' },
    {value: [] , name: 'Branch of knowlege' },
    {value: [] , name: 'Capote' },
    {value: [] , name: 'Chains of others' },
    {value: [] , name: 'CrowCrow`s Eye View' },
    {value: [] , name: 'Dimension shredder' },
    {value: [] , name: 'Ebony stem' },
    {value: [] , name: 'Fluid sac' },
    {value: [] , name: 'Impending day' },
    {value: [] , name: 'La sangre de sancho' },
    {value: [] , name: 'Land of illusion' },
    {value: [] , name: 'Lantern' },
    {value: [] , name: 'Lifetime stew' },
    {value: [] , name: 'Pursuance' },
    {value: [] , name: 'Red eyes' },
    {value: [] , name: 'Red eyes (open)' },
    {value: [] , name: 'Regret' },
    {value: [] , name: 'Representation emitter' },
    {value: [] , name: 'Rime shank' },
    {value: [] , name: 'Roseate desire' },
    {value: [] , name: 'Forest for the Flames' },
    {value: [], name: 'Screwloose wallop' },
    {value: [] , name: 'Snagharpoon' },
    {value: [] , name: 'Soda' },
    {value: [] , name: 'Suddenly, One Day' },
    {value: [] , name: 'Sunshower' },
    {value: [] , name: 'Telepole' },
    {value: [] , name: 'To Páthos Máthos' },
    {value: [] , name: 'What is cast' },
    {value: [] , name: 'Wishing cairn' },
    {value: [] , name: 'Ya Śūnyatā Tad Rūpam' },
    {value: [] , name: 'Legerdemain' },
]