
export const LCEGOList = [

    {value: '4th match flame' , name: '4th match flame' },
    {value: 'AEDD', name: 'AEDD' },
    {value: 'Ardor blossom star' , name: 'Ardor blossom star' },
    {value: 'Bodysack' , name: 'Bodysack' },
    {value: 'Branch of knowlege' , name: 'Branch of knowlege' },
    {value: 'Capote' , name: 'Capote' },
    {value: 'Chains of others' , name: 'Chains of others' },
    {value: 'Crow`s Eye View' , name: 'Crow`s Eye View' },
    {value: 'Dimension shredder' , name: 'Dimension shredder' },
    {value: 'Ebony stem' , name: 'Ebony stem' },
    {value: 'Fluid sac' , name: 'Fluid sac' },
    {value: 'Impending day' , name: 'Impending day' },
    {value: 'La sangre de sancho' , name: 'La sangre de sancho' },
    {value: 'Land of illusion' , name: 'Land of illusion' },
    {value: 'Lantern' , name: 'Lantern' },
    {value: 'Lifetime stew' , name: 'Lifetime stew' },
    {value: 'Pursuance' , name: 'Pursuance' },
    {value: 'Red eyes' , name: 'Red eyes' },
    {value: 'Red eyes (open)' , name: 'Red eyes (open)' },
    {value: 'Regret' , name: 'Regret' },
    {value: 'Representation emitter' , name: 'Representation emitter' },
    {value: 'Rime shank' , name: 'Rime shank' },
    {value: 'Roseate desire' , name: 'Roseate desire' },
    {value: 'Forest for the Flames' , name: 'Forest for the Flames' },
    {value: 'Screwloose wallop' , name: 'Screwloose wallop' },
    {value: 'Snagharpoon' , name: 'Snagharpoon' },
    {value: 'Soda' , name: 'Soda' },
    {value: 'Suddenly, One Day' , name: 'Suddenly, One Day' },
    {value: 'Sunshower' , name: 'Sunshower' },
    {value: 'Telepole' , name: 'Telepole' },
    {value: 'To Páthos Máthos' , name: 'To Páthos Máthos' },
    {value: 'What is cast' , name: 'What is cast' },
    {value: 'Wishing cairn' , name: 'Wishing cairn' },
    {value: 'Ya Śūnyatā Tad Rūpam' , name: 'Ya Śūnyatā Tad Rūpam' },
    {value: 'Legerdemain' , name: 'Legerdemain' },
]